version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./api:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - phpmyadmin
      - supervisor
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./api:/var/www/html:delegated
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:delegated
  mysql:
    image: 'mariadb:latest'
    env_file:
      - ./env/mysql.env
    volumes:
      - maria:/var/lib/mysql
    depends_on:
      - php
  phpmyadmin:
    image: 'phpmyadmin:latest'
    env_file:
      - ./env/phpmyadmin.env
    ports:
      - '3300:80'
    depends_on:
      - mysql
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./api:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./api:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
  supervisor:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./api:/var/www/html
    entrypoint: ['/usr/bin/supervisord', '-n']
    depends_on:
      - php
  nuxt:
    image: node:current-alpine
    working_dir: /var/www/html
    user: node
    command: sh -c 'npm run dev'
    volumes:
      - ./client:/var/www/html
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
networks:
  default:
    name: tpg
    driver: bridge
volumes:
  maria:
    external: true
